Models/Pergunta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aula01.Models
{
    public class Pergunta
    {
        public int Id { get; set; }        
        public string Autor { get; set; }

        [Required]
        public string Descricao { get; set; }
    }
}

Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Aula01.Controllers
{
    public class AutorController : Controller
    {
        public IActionResult Index(string nome)
        {
            return View();
        }

        public  IActionResult ListaDosAutoresDoAno(int ano)
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Aula01.Data;
using Aula01.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aula01.Controllers
{
    public class HomeController : Controller
    {
        private PerguntaContext _context;

        public HomeController(PerguntaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //ViewBag.Nome = "Flavio";
            //ViewData["NomDoAluno"] = $"Outro nome {DateTime.Now}";                    
            
            return View(_context.Pergunta.ToList());
        }
        public IActionResult Sobre()
        {
            return View();
        }
        public IActionResult Ajuda()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Pergunta pergunta)
        {
            if (ModelState.IsValid)
            {
                _context.Pergunta.Add(pergunta);
                await _context.SaveChangesAsync();            
            }
            return View();
        }

    }
}

Controllers/PerguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Aula01.Data;
using Aula01.Models;

namespace Aula01.Controllers
{
    public class PerguntasController : Controller
    {
        private readonly PerguntaContext _context;

        public PerguntasController(PerguntaContext context)
        {
            _context = context;
        }

        // GET: Perguntas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pergunta.ToListAsync());
        }

        // GET: Perguntas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Pergunta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pergunta == null)
            {
                return NotFound();
            }

            return View(pergunta);
        }

        // GET: Perguntas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Perguntas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Autor,Descricao")] Pergunta pergunta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pergunta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pergunta);
        }

        // GET: Perguntas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Pergunta.FindAsync(id);
            if (pergunta == null)
            {
                return NotFound();
            }
            return View(pergunta);
        }

        // POST: Perguntas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Autor,Descricao")] Pergunta pergunta)
        {
            if (id != pergunta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pergunta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerguntaExists(pergunta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pergunta);
        }

        // GET: Perguntas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Pergunta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pergunta == null)
            {
                return NotFound();
            }

            return View(pergunta);
        }

        // POST: Perguntas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pergunta = await _context.Pergunta.FindAsync(id);
            _context.Pergunta.Remove(pergunta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerguntaExists(int id)
        {
            return _context.Pergunta.Any(e => e.Id == id);
        }
    }
}

Controllers/TopicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Aula01.Controllers
{
    public class TopicoController : Controller
    {
        public IActionResult Index(string categoria, string topico)
        {
            return View();
        }
    }
}

ViewComponents/NoticiasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aula01.ViewComponents
{
    public class NoticiasViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int total, bool noticiasUrgentes = false)
        {
            var view = noticiasUrgentes ? "noticiasUrgentes":"noticias";
            var itens = GetItems(total);

            return View(view, itens);
        }

        private IEnumerable<Noticia> GetItems(int total)
        {
            for (int i = 0; i <= total; i++)
                yield return new Noticia() { Id = i + 1, Titulo = $"Noticia sobre {i}"};
        }

        public class Noticia
        {
            public int Id { get; set; }
            public string Titulo { get; set; }
            public string Link { get; set; }
        }
    }
}

Views/Home/Ajuda.cshtml
    <h1>Ajuda! @DateTime.Now.ToString()</h1>
    <p>Twitter @@Flavolho</p>

Views/Home/Create.cshtml
@model Pergunta
@{
    Layout = "_Layout";
}

<form action="/home/create" method="post">
    @Html.EditorFor(a => a.Descricao)
    @*Descrição
        <input type="text" name="Descricao" value="" />
        <br />
        Autor
        <input type="text" name="Autor" value="" />
        <br />*@
    <input type="submit" name="Salvar" value="Salvar" />
    @Html.ValidationSummary()
</form>


<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"></script>

Views/Home/Index.cshtml
@model IEnumerable<Pergunta>
@{
    Layout = "_LayoutB";
}

<email mail-to-mommy="João.Roberto"></email>


<vc:noticias total="10" noticias-urgentes="false"></vc:noticias>
@*@await Component.InvokeAsync("Noticias", new { total = 3 });*@

<h1>ViewBag @ViewBag.Nome</h1>
<h1>ViewData @ViewData["NomeDoAluno"]</h1>

<ul>
    @foreach (var item in Model)
    {
        <li>
            <p>@item.Id</p>
            <p>@item.Autor</p>
            <p>@item.Descricao</p>
        </li>
    }
</ul>

<img src="~/brazzers.png" />    <br />
<img src="~/salty.gif" />

<p>Twitter @@Flavolho</p>


@*<p>@Model.Id</p>
    <p>@Model.Autor</p>
    <p>@Model.Descricao</p>*@

Views/Home/Sobre.cshtml
    <h1>Sobre! @DateTime.Now.ToString()</h1>
    <p>Twitter @@Flavolho</p>

Views/Perguntas/Create.cshtml
@model Aula01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Pergunta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Views/Perguntas/Delete.cshtml
@model Aula01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pergunta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Perguntas/Details.cshtml
@model Aula01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Pergunta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/Perguntas/Edit.cshtml
@model Aula01.Models.Pergunta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Pergunta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Views/Perguntas/Index.cshtml
@model IEnumerable<Aula01.Models.Pergunta>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Views/Shared/Components/Noticias/Noticias.cshtml
@model IEnumerable<Aula01.ViewComponents.NoticiasViewComponent.Noticia>
<ul>
    @foreach (var item in Model)
    {
        <li>
            @item.Titulo
        </li>
    }
</ul>

Views/Shared/Components/Noticias/NoticiasUrgentes.cshtml
@model IEnumerable<Aula01.ViewComponents.NoticiasViewComponent.Noticia>
<ul>
    @foreach (var item in Model)
    {
        <li style="background-color:red">
            @item.Titulo
        </li>
    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <partial name="_menu" />

    @RenderBody()

    <footer>assumir</footer>

</body>
</html>

Views/Shared/_LayoutB.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <partial name="_menu" />
    
    Layout B

    @RenderBody()

    <footer>assumir</footer>

</body>
</html>

Views/Shared/_menu.cshtml
<nav>
    <ul>
        <li><a href="/Home/Index">Home</a></li>
        <li><a href="/Home/Sobre">Sobre</a></li>
        <li><a href="/Home/Ajuda">Ajuda</a></li>
        <li><a href="/Home/Create">Create</a></li>
    </ul>
</nav>